const char* heroNames[98] = {
    "Abbathor", "Aerdrie Faenya", "Arvoreen", "Baervan Wildwanderer",
    "Baravar Cloakshadow", "Berronar Truesilver", "Brandobaris",
    "Callarduran Smoothhands", "Charmalaine", "Clangeddin Silverbeard",
    "Corellon Larethian", "Cyrrollalee", "Deep Sashelas",
    "Dugmaren Brightmantle", "Dumathoin", "Ehlonna", "Erevan Ilesere",
    "Fenmarel Mestarine", "Fharlanghn", "Flandal Steelskin", "Gadhelyn",
    "Gaerdal Ironhand", "Garl Glittergold", "Gendwar Argrim",
    "Halani Celanil", "Heironeous", "Labelas Enoreth", "Moradin",
    "Muamman Duathal", "Olidammara", "Pelor",   "Rillifane Rallathil",
    "Roykyn", "Segojan Earthcaller", "Sehanine Moonbow", "Sheela Peryroyl",
    "Solonor Thelandira", "St. Cuthbert", "Urdlen", "Urogalan", "Vergadain",
    "Ye'Cind", "Yondalla", "Annam", "Bahamut", "Blibdoolpoolp", "Diirinka",
    "Eadro", "Gruumsh", "Hruggek", "Ilsensine", "Jubilex", "Kurtulmak",
    "Laduguer", "Loagzed", "Lolth", "Maglubiyet", "Merrshaulk", "Orcus",
    "Sekolah", "Semuanya", "Shekinester", "Skerrit", "Stronmaus", "Tiamat",
    "Vaprak", "Yeenoghu", "Aasterinian", "Bagrivyek", "Bahgtru",
    "Chronepsis", "Doresain", "Falazure", "Gaknulak", "Grankhul",
    "Great Mother", "Grolantor", "Hiatea", "Iallanis", "Ilneval", "Io",
    "Karontor", "Kiaransalee", "Khurgorbaeyag", "Luthic", "Memnor",
    "Nomog-Geaya", "Panzuriel", "Raxivort", "Shargaas", "Sixin",
    "Skoraeus Stonebones", "Squerrik", "Surtr", "Thrym", "Vhaeraun",
    "Yurtrus", "Zinzerena"
};

const char* weaponNames[119] = {
    "Caladbolg", "Taming Sword", "Crystal Sword", "Excalibur", "Ragnarok",
    "Balmung", "Save the Queen", "Heartbreaker", "Lionheart", "Durandal",
    "Ascalon", "Ambitious", "Hrunting", "Astral Sword", "Apocalypse",
    "Slowstrike",
"Master Sword",
"Rune-Master",
"Warlock",
"Arc Sword",
"Gilventure",
"Tri-Steel",
"Helter-Skelter",
"Vendetta",
"Avenger",
"Prism Steel",
"Mirage Sword",
"Lifesaver",
"Sonic Steel",
"Vigilante",
"Dance Macabre",
"Largamente",
"Gravestone",
"Sidewinder",
"Nightmare",
"Mage Masher",
"Nightbringer",
"Knight Sword",
"Wizard Sword",
"Double-Edge",
"Razzmatazz",
"Deathbringer",
"Stunning Steel",
"Basilisk Steel",
"Poison Steel",
"Lullaby Steel",
"Muted Steel",
"Twilight Steel",
"Hunter's Sword",
"Flametongue",
"Ice Brand",
"Lightning Steel",
"Force Saber",
"Baroque Sword",
"Sorcery Sword",
"Soldier's Saber",
"Rune Steel",
"Enchanted Sword",
"Fencing Saber",
"Slasher",
"Nirvana",
"Herding Staff",
"Arc Arcana",
"Abraxas",
"Heavenly Axis",
"Judgment",
"Seraphim Rod",
"Rod of Roses",
"Nimbus Rod",
"Wing Wand",
"Wonder Wand",
"Laevatein",
"Astral Rod",
"Chaos Rod",
"Power Staff",
"Shining Staff",
"Faerie Staff",
"Magistral Rod",
"El Dorado",
"Tri-Rod",
"Wicked Wand",
"Nemesis Rod",
"Defender",
"Prism Rod",
"Mirage Rod",
"Healing Rod",
"Wind Rod",
"Conductor",
"Punisher",
"Calcite Staff",
"Bizarre Staff",
"Staff of Thorns",
"Reticent Staff",
"Darkness Staff",
"Monk Staff",
"Mage's Staff",
"Dual Rod",
"Ominous Rod",
"Death Wand",
"Entangling Rod",
"Break Rod",
"Belladonna Wand",
"Lullaby Rod",
"Rod of Silence",
"Rod of Darkness",
"Rod of Wisdom",
"Rod of Fire",
"Rod of Ice",
"Rod of Lightning",
"Rod of Water",
"Malleable Staff",
"Force Rod",
"Ductile Rod",
"Sorcery Rod",
"Full Metal Rod",
"Rune Rod",
"Enchanted Rod",
"Rod of Striking",
"Spiked Rod",
};